name: Clone Repositories

on:
  workflow_dispatch:
    inputs:
      repo_urls:
        description: "List of repository URLs to clone"
        required: true
        default: '[\"https://github.com/iabdsam/test1\", \"https://github.com/iabdsam/test2\"]'
        type: string

jobs:
  clone_repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Convert repo_urls input to array
        id: convert
        run: echo "::set-output name=repos::$(echo ${{ github.event.inputs.repo_urls }} | jq -c .)"

      - name: Clone repositories
        run: |
          repos='${{ steps.convert.outputs.repos }}'
          echo "Current directory before cloning: $(pwd)"
          for repo in $(echo $repos | jq -r '.[]'); do
            folder_name=$(basename $repo)
            echo "Cloning repository: $repo into folder: $folder_name"
            git clone -n --depth=1 --filter=tree:0 $repo $GITHUB_WORKSPACE/$folder_name
            if [ -d "$GITHUB_WORKSPACE/$folder_name" ]; then
              echo "Successfully cloned $repo into $GITHUB_WORKSPACE/$folder_name"
            else
              echo "Failed to clone $repo"
            fi
            cd $GITHUB_WORKSPACE/$folder_name
            git sparse-checkout set --no-cone /dist
            git checkout
            cd $GITHUB_WORKSPACE
            git add $GITHUB_WORKSPACE/$folder_name
          done
          git commit -m "update"
          git push origin main
          echo "Current directory after cloning: $(pwd)"
